#!/usr/bin/env php
<?php

declare(strict_types=1);

use Bee\Core\Cli\CliApplication;
use Bee\Core\Cli\CoreStatusCommand;
use Bee\Core\Cli\CreateControllerCommand;
use Bee\Core\Cli\CreateModelCommand;
use Bee\Core\Cli\CreateViewCommand;
use Bee\Core\Cli\GenerateInstanceKeysCommand;
use Bee\Core\Creator\ComponentScaffolder;
use Bee\Core\Security\InstanceKeyManager;

$arguments = array_slice($argv ?? [], 1);
$applicationRoot = __DIR__;

foreach ($arguments as $index => $argument) {
    if (str_starts_with($argument, '--root=')) {
        $applicationRoot = substr($argument, 7);
        unset($arguments[$index]);
    }
}
$arguments = array_values($arguments);

$application = require $applicationRoot . '/app/bootstrap/cli.php';
$cli = new CliApplication();
$cli->add(new CoreStatusCommand($application));
$creator = $application->services->get(ComponentScaffolder::class);
$cli->add(new CreateControllerCommand($creator));
$cli->add(new CreateModelCommand($creator));
$cli->add(new CreateViewCommand($creator));
$cli->add(new GenerateInstanceKeysCommand($application->root, new InstanceKeyManager()));

exit($cli->run($arguments));
