### ----------------------------------------------------
### ----------------------------------------------------
### Extensión requerida: REST Client para VS Code
### ----------------------------------------------------
### ----------------------------------------------------
@privateKey = 51362e-0cb1b9-f9c183-17b0a3-1a002e

### CARGAR TODOS LOS POSTS
GET http://localhost:8848/Bee-Framework/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{privateKey}}
### ----------------------------------------------------

### CARGAR UN POST
GET http://localhost:8848/Bee-Framework/api/posts/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{privateKey}}
### ----------------------------------------------------

### AGREGAR NUEVO POST
# @prompt nombre
# @prompt titulo El título de la entrada
# @prompt contenido El contenido de la entrada
POST http://localhost:8848/Bee-Framework/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{privateKey}}

{
  "nombre"  : "{{nombre}}",
  "titulo": "{{titulo}}",
  "contenido": "{{contenido}}"
}
### ----------------------------------------------------

### ACTUALIZAR POST
PUT http://localhost:8848/Bee-Framework/api/posts/12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{privateKey}}

{
  "nombre"  : "VSCode",
  "titulo": "Nueva noticia desde VSCode Editada",
  "contenido": "Editado desde REST Client."
}
### ----------------------------------------------------

### BORRAR UN POST
DELETE  http://localhost:8848/Bee-Framework/api/posts/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{privateKey}}
### ----------------------------------------------------

### TEST AJAX
GET http://localhost:8848/Bee-Framework/ajax/test HTTP/1.1
Content-Type: application/json
### ----------------------------------------------------