<article class="bee-docs-content">
  <section id="inicio" class="bee-docs-section"><span class="bee-docs-kicker">01 · Inicio</span><h2>Primeros pasos</h2><p>Bee requiere PHP 8.2+, Composer y MySQL/MariaDB. Instala dependencias, configura el entorno y verifica el núcleo sin depender de una petición HTTP.</p><?= code_block("composer --working-dir=app install\nphp bee core:status") ?><div class="alert alert-primary" role="note"><strong>Empieza rápido.</strong> Usa <a class="alert-link" href="creator">Bee Creator</a> o ejecuta <code>php bee create:controller Blog --view</code>.</div></section>

  <section id="estructura" class="bee-docs-section"><span class="bee-docs-kicker">02 · Arquitectura</span><h2>Responsabilidades bien separadas</h2><div class="row g-3">
    <?php foreach ([['app/bootstrap/', 'Bootstraps común, HTTP, CLI, cron, testing y updater.'], ['app/routes/', 'Rutas web, API y middleware.'], ['app/controllers/', 'Coordina servicios, modelos y respuestas.'], ['app/models/', 'Datos mediante BeeModel y consultas preparadas.'], ['templates/views/', 'Vistas PHP o Twig sin lógica de negocio.'], ['app/src/Core/', 'Componentes nuevos con namespace y PSR-4.']] as [$path, $description]): ?>
      <div class="col-12 col-md-6"><div class="border rounded-3 p-3 h-100"><code class="fw-bold"><?= htmlspecialchars($path, ENT_QUOTES, 'UTF-8') ?></code><p class="small text-secondary mt-2 mb-0"><?= htmlspecialchars($description, ENT_QUOTES, 'UTF-8') ?></p></div></div>
    <?php endforeach; ?>
  </div></section>

  <section id="configuracion" class="bee-docs-section"><span class="bee-docs-kicker">03 · Configuración</span><h2>Una configuración, responsabilidades claras</h2><p>Bee construye un único objeto <code>Configuration</code>: carga los valores versionados de <code>app/config/defaults.php</code>, aplica los valores de instalación de <code>app/config/.env</code> y finalmente cualquier override explícito del bootstrap. <code>identity.php</code> conserva únicamente la identidad y versiones.</p><div class="row g-3 mb-4"><div class="col-12 col-md-4"><div class="border rounded-3 p-3 h-100"><strong>defaults.php</strong><p class="small text-secondary mb-0 mt-2">Defaults internos, plugins, cookies y convenciones.</p></div></div><div class="col-12 col-md-4"><div class="border rounded-3 p-3 h-100"><strong>.env</strong><p class="small text-secondary mb-0 mt-2">Secretos, credenciales, paths y diferencias por instalación.</p></div></div><div class="col-12 col-md-4"><div class="border rounded-3 p-3 h-100"><strong>identity.php</strong><p class="small text-secondary mb-0 mt-2">ID estable, versiones y formato de paquetes.</p></div></div></div><p>La versión de la aplicación tiene una sola fuente: <code>identity.php → product_version</code>. Se consulta con <code>config()->identity->productVersion</code> o <code>get_product_version()</code>; <code>get_version()</code> permanece como alias legacy. <code>APP_VERSION</code> no debe declararse en <code>.env</code>.</p><p><code>.env.example</code> y las instalaciones nuevas siguen un orden canónico: runtime, identidad visual, secretos, API, autenticación, correo, integraciones, base de datos de desarrollo, producción y variables propias. Las variables personalizadas pueden agregarse sin registrarlas en el core. Usa <code>config()</code>, <code>option()</code> para la tabla <code>options</code>, o inyecta <code>Configuration</code>.</p>
    <?= code_block("// app/config/.env\nITEMS_PER_PAGE=20\n\n\$limit = (int) config('ITEMS_PER_PAGE', '15');\n\$color = option('brand_color', '#f6b900');") ?>
    <?= code_block("use Bee\\Core\\Config\\Configuration;\n\nfinal class reportController extends Controller\n{\n    public function __construct(private readonly Configuration \$configuration)\n    {\n        parent::__construct();\n    }\n}") ?><p class="small text-secondary">Las constantes permanecen únicamente como compatibilidad temporal.</p></section>

  <section id="rutas" class="bee-docs-section"><span class="bee-docs-kicker">04 · HTTP</span><h2>Routing moderno y expresivo</h2><p>Registra rutas directamente en <code>app/routes/web.php</code> o <code>app/routes/api.php</code>. Hay verbos HTTP, parámetros, restricciones, nombres, middleware y grupos.</p>
    <?= code_block("use Bee\\Core\\Routing\\Route;\n\nRoute::get('/articles', [articleController::class, 'index'])->name('articles.index');\nRoute::post('/articles', [articleController::class, 'store'])->middleware('csrf');\nRoute::get('/articles/{slug}', [articleController::class, 'show'])\n    ->where('slug', '[a-z0-9]+(?:-[a-z0-9]+)*')\n    ->name('articles.show');\n\n\$url = route('articles.show', ['slug' => 'hola-bee']);") ?>
    <?= code_block("Route::prefix('/admin')->name('admin.')->middleware('auth')->group(function (): void {\n    Route::get('/users', [userController::class, 'index'])->name('users.index');\n});") ?><p>Si ninguna ruta moderna coincide, Bee conserva el despacho legacy por URL.</p></section>

  <section id="controladores" class="bee-docs-section"><span class="bee-docs-kicker">05 · MVC</span><h2>Controladores y vistas con el flujo Bee</h2><p>Extiende <code>Controller</code> para definir título, directorio, vista y datos. <code>renderToString()</code> devuelve HTML compatible con el router moderno. En vistas PHP, los datos se consultan desde <code>$d</code> mediante propiedades —por ejemplo, <code>$d->article->title</code>— para conservar el contrato legacy del renderizador.</p>
    <?= code_block("final class articlePageController extends Controller\n{\n    public function __construct()\n    {\n        parent::__construct();\n        \$this->setViewDirectory('articles');\n    }\n\n    public function show(string \$slug): string\n    {\n        \$article = articleModel::where('slug', \$slug)->first();\n        \$this->setTitle((string) \$article->title);\n        \$this->setView('show');\n        \$this->setData(['article' => \$article->toArray()]);\n        return \$this->renderToString();\n    }\n}") ?><p>La vista vive en <code>templates/views/articles/showView.php</code>. Escapa siempre el contenido generado por usuarios.</p></section>

  <section id="modelos" class="bee-docs-section"><span class="bee-docs-kicker">06 · Datos</span><h2>BeeModel como ORM ligero</h2><p>Define tabla, campos asignables, casts y timestamps. Las consultas encadenables usan parámetros preparados y devuelven modelos.</p>
    <?= code_block("final class articleModel extends BeeModel\n{\n    protected string \$table = 'articles';\n    protected array \$fillable = ['title', 'slug', 'status', 'views'];\n    protected array \$guarded = ['id'];\n    protected array \$casts = ['views' => 'integer'];\n    protected bool \$timestamps = true;\n}\n\n\$article = articleModel::create(\$validated);\n\$published = articleModel::where('status', 'published')\n    ->orderBy('created_at', 'desc')->limit(10)->get();\n\$article->title = 'Nuevo título';\n\$article->save();") ?><p>También incluye <code>find()</code>, <code>whereIn()</code>, <code>whereNull()</code>, <code>count()</code>, <code>exists()</code>, <code>paginate()</code>, <code>update()</code> y <code>delete()</code>.</p></section>

  <section id="api" class="bee-docs-section"><span class="bee-docs-kicker">07 · Integración</span><h2>APIs JSON y JavaScript asíncrono</h2><p>Las rutas de <code>api.php</code> entregan respuestas y errores JSON. En el navegador valida <code>response.ok</code> y maneja los fallos.</p><?= code_block("const response = await fetch('api/articles');\nconst payload = await response.json();\nif (!response.ok) {\n  throw new Error(payload.message ?? 'No fue posible cargar los artículos');\n}\nconsole.log(payload.data);") ?><a class="btn btn-outline-primary" href="examples/articles">Explorar el CRUD completo</a></section>

  <section id="cli" class="bee-docs-section"><span class="bee-docs-kicker">08 · Automatización</span><h2>CLI sin simular HTTP</h2><p><code>bee</code> carga configuración y servicios sin iniciar sesión, ejecutar <code>Bee::fly()</code> ni despachar controladores.</p><?= code_block("php bee core:status\nphp bee security:keys\nphp bee create:controller Orders --view\nphp bee create:model Order --table=orders --fields=number:string,total:decimal,status:string\nphp bee create:view orders/show\nphp bee create:view emails/receipt --twig") ?><h3 class="h5 mt-4">Salts y claves de instancia</h3><p>En un proyecto nuevo, <code>security:keys</code> crea <code>app/config/.env</code> desde la plantilla si hace falta y genera <code>AUTH_SALT</code>, <code>NONCE_SALT</code>, <code>API_PUBLIC_KEY</code> y <code>API_PRIVATE_KEY</code> con <code>random_bytes()</code>. Nunca imprime los secretos ni sobrescribe valores reales.</p><?= code_block("# Instalación nueva\nphp bee security:keys\n\n# Rotación deliberada; crea un respaldo del .env\nphp bee security:keys --force") ?><div class="alert alert-warning mb-0" role="note"><strong>Rota con cuidado.</strong> Cambiar <code>AUTH_SALT</code> puede invalidar contraseñas existentes; cambiar nonces o API keys invalida sesiones, tokens y clientes integrados. Conserva el respaldo hasta completar la migración.</div></section>

  <section id="seguridad" class="bee-docs-section"><span class="bee-docs-kicker">09 · Seguridad</span><h2>Valida, sanitiza y autoriza</h2><p>Sanitizar no reemplaza validar. Protege operaciones con CSRF y middleware, usa consultas preparadas y comprueba la autorización sobre cada recurso.</p><?= code_block("\$name = sanitize_name(\$_POST['name'] ?? '');\n\$email = sanitize_email(\$_POST['email'] ?? '');\n\$phone = sanitize_phone(\$_POST['phone'] ?? '');\n\$address = sanitize_address(\$_POST['address'] ?? '');\n\$amount = sanitize_money(\$_POST['amount'] ?? null);\n\$slug = sanitize_slug(\$_POST['title'] ?? '');") ?></section>

  <section id="compatibilidad" class="bee-docs-section"><span class="bee-docs-kicker">10 · Migración</span><h2>Convive con el código existente</h2><p>Los controladores legacy, rutas automáticas, constantes y modelos anteriores siguen funcionando. Migra gradualmente: usa los helpers de configuración, registra rutas modernas, conserva <code>Controller</code>/<code>View</code> y moderniza modelos cuando lo necesites.</p><p>Bee mantiene temporalmente la etiqueta <code>&lt;base&gt;</code> para resolver rutas y assets relativos heredados. Para enlaces internos puedes escribir <code>href="#seccion"</code>: el framework los normaliza a la URL actual. En vistas PHP también puedes generar el destino explícitamente con <code>new_anchor('seccion')</code>.</p></section>

  <section id="actualizaciones" class="bee-docs-section bee-docs-section-highlight"><span class="bee-docs-kicker">Documentación viva</span><h2>Novedades de Bee 1.6.0</h2><p>Esta página forma parte del producto: cada mejora pública debe actualizar su sección y añadir una entrada al changelog del README.</p><ul class="mb-0"><li>Índice de documentación con scroll spy y navegación activa.</li><li>Bloques de código con lenguaje, resaltado de sintaxis y copia directa.</li><li>Bootstraps separados para HTTP, CLI, cron, testing y updater.</li><li>Router nombrado con middleware y compatibilidad legacy.</li><li><code>config()</code>, <code>option()</code> e inyección tipada.</li><li>BeeModel moderno, Creator y CRUD de artículos.</li><li>Tema Bootstrap 5 y panel administrativo Bee.</li></ul></section>
</article>
